## Import Libraries

In [62]:
import pandas as pd
import numpy as np
import time

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import SGDClassifier
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.dummy import DummyClassifier
from sklearn.model_selection import GridSearchCV, TimeSeriesSplit

from sklearn.metrics import roc_auc_score
from sklearn.metrics import average_precision_score
from sklearn.metrics import precision_recall_curve

## Load Data

In [31]:
df = pd.read_excel("diabetic_data.xlsx")
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [32]:
df.shape

(101766, 50)

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  str
 3   gender                    101766 non-null  str
 4   age                       101766 non-null  str
 5   weight                    101766 non-null  str
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  str
 11  medical_specialty         101766 non-null  str
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  object
 19  diag_2                    101766 non-null  object
 20  diag_3                    101766 non-null  object
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             5346 non-null    str
 23  A1Cresult                 17018 non-null   str
 24  metformin                 101766 non-null  str
 25  repaglinide               101766 non-null  str
 26  nateglinide               101766 non-null  str
 27  chlorpropamide            101766 non-null  str
 28  glimepiride               101766 non-null  str
 29  acetohexamide             101766 non-null  str
 30  glipizide                 101766 non-null  str
 31  glyburide                 101766 non-null  str
 32  tolbutamide               101766 non-null  str
 33  pioglitazone              101766 non-null  str
 34  rosiglitazone             101766 non-null  str
 35  acarbose                  101766 non-null  str
 36  miglitol                  101766 non-null  str
 37  troglitazone              101766 non-null  str
 38  tolazamide                101766 non-null  str
 39  examide                   101766 non-null  str
 40  citoglipton               101766 non-null  str
 41  insulin                   101766 non-null  str
 42  glyburide-metformin       101766 non-null  str
 43  glipizide-metformin       101766 non-null  str
 44  glimepiride-pioglitazone  101766 non-null  str
 45  metformin-rosiglitazone   101766 non-null  str
 46  metformin-pioglitazone    101766 non-null  str
 47  change                    101766 non-null  str
 48  diabetesMed               101766 non-null  str
 49  readmitted                101766 non-null  str
dtypes: int64(13), object(3), str(34)
memory usage: 38.8+ MB

In [34]:
df.describe()

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,1.017660e+05,1.017660e+05,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000
mean,1.652016e+08,5.433040e+07,2.024006,3.715642,5.754437,4.395987,43.095641,1.339730,16.021844,0.369357,0.197836,0.635566,7.422607
std,1.026403e+08,3.869636e+07,1.445403,5.280166,4.064081,2.985108,19.674362,1.705807,8.127566,1.267265,0.930472,1.262863,1.933600
min,1.252200e+04,1.350000e+02,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,8.496119e+07,2.341322e+07,1.000000,1.000000,1.000000,2.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,1.523890e+08,4.550514e+07,1.000000,1.000000,7.000000,4.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,2.302709e+08,8.754595e+07,3.000000,4.000000,7.000000,6.000000,57.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,4.438672e+08,1.895026e+08,8.000000,28.000000,25.000000,14.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000

In [35]:
for col in df.columns:
    print(f"\n=== {col} ===")
    print(df[col].value_counts(dropna=False))

=== encounter_id ===
encounter_id
2278392      1
149190       1
64410        1
500364       1
16680        1
            ..
443847548    1
443847782    1
443854148    1
443857166    1
443867222    1
Name: count, Length: 101766, dtype: int64

=== patient_nbr ===
patient_nbr
88785891     40
43140906     28
1660293      23
23199021     23
88227540     23
             ..
183087545     1
188574944     1
140199494     1
120975314     1
175429310     1
Name: count, Length: 71518, dtype: int64

=== race ===
race
Caucasian          76099
AfricanAmerican    19210
?                   2273
Hispanic            2037
Other               1506
Asian                641
Name: count, dtype: int64

=== gender ===
gender
Female             54708
Male               47055
Unknown/Invalid        3
Name: count, dtype: int64

=== age ===
age
[70-80)     26068
[60-70)     22483
[50-60)     17256
[80-90)     17197
[40-50)      9685
[30-40)      3775
[90-100)     2793
[20-30)      1657
[10-20)       691
[0-10)        161
Name: count, dtype: int64

=== weight ===
weight
?            98569
[75-100)      1336
[50-75)        897
[100-125)      625
[125-150)      145
[25-50)         97
[0-25)          48
[150-175)       35
[175-200)       11
>200             3
Name: count, dtype: int64

=== admission_type_id ===
admission_type_id
1    53990
3    18869
2    18480
6     5291
5     4785
8      320
7       21
4       10
Name: count, dtype: int64

=== discharge_disposition_id ===
discharge_disposition_id
1     60234
3     13954
6     12902
18     3691
2      2128
22     1993
11     1642
5      1184
25      989
4       815
7       623
23      412
13      399
14      372
28      139
8       108
15       63
24       48
9        21
17       14
16       11
19        8
10        6
27        5
12        3
20        2
Name: count, dtype: int64

=== admission_source_id ===
admission_source_id
7     57494
1     29565
17     6781
4      3187
6      2264
2      1104
5       855
3       187
20      161
9       125
8        16
22       12
10        8
14        2
11        2
25        2
13        1
Name: count, dtype: int64

=== time_in_hospital ===
time_in_hospital
3     17756
2     17224
1     14208
4     13924
5      9966
6      7539
7      5859
8      4391
9      3002
10     2342
11     1855
12     1448
13     1210
14     1042
Name: count, dtype: int64

=== payer_code ===
payer_code
?     40256
MC    32439
HM     6274
SP     5007
BC     4655
MD     3532
CP     2533
UN     2448
CM     1937
OG     1033
PO      592
DM      549
CH      146
WC      135
OT       95
MP       79
SI       55
FR        1
Name: count, dtype: int64

=== medical_specialty ===
medical_specialty
?                         49949
InternalMedicine          14635
Emergency/Trauma           7565
Family/GeneralPractice     7440
Cardiology                 5352
                          ...
Dermatology                   1
SportsMedicine                1
Speech                        1
Perinatology                  1
Neurophysiology               1
Name: count, Length: 73, dtype: int64

=== num_lab_procedures ===
num_lab_procedures
1      3208
43     2804
44     2496
45     2376
38     2213
       ...
120       1
132       1
121       1
126       1
118       1
Name: count, Length: 118, dtype: int64

=== num_procedures ===
num_procedures
0    46652
1    20742
2    12717
3     9443
6     4954
4     4180
5     3078
Name: count, dtype: int64

=== num_medications ===
num_medications
13    6086
12    6004
11    5795
15    5792
14    5707
      ...
70       2
75       2
81       1
79       1
74       1
Name: count, Length: 75, dtype: int64

=== number_outpatient ===
number_outpatient
0     85027
1      8547
2      3594
3      2042
4      1099
5       533
6       303
7       155
8        98
9        83
10       57
11       42
13       31
12       30
14       28
15       20
16       15
17        8
20        7
21        7
18        5
22        5
19        3
27        3
24        3
35        2
29        2
36        2
26        2
33        2
25        2
23        2
42        1
39        1
34        1
28        1
37        1
38        1
40        1
Name: count, dtype: int64

=== number_emergency ===
number_emergency
0     90383
1      7677
2      2042
3       725
4       374
5       192
6        94
7        73
8        50
10       34
9        33
11       23
13       12
12       10
22        6
16        5
18        5
20        4
19        4
15        3
14        3
25        2
21        2
42        1
28        1
46        1
76        1
37        1
64        1
63        1
54        1
24        1
29        1
Name: count, dtype: int64

=== number_inpatient ===
number_inpatient
0     67630
1     19521
2      7566
3      3411
4      1622
5       812
6       480
7       268
8       151
9       111
10       61
11       49
12       34
13       20
14       10
15        9
16        6
19        2
17        1
21        1
18        1
Name: count, dtype: int64

=== diag_1 ===
diag_1
428    6862
414    6581
786    4016
410    3614
486    3508
       ...
833       1
391       1
690       1
10        1
V51       1
Name: count, Length: 717, dtype: int64

=== diag_2 ===
diag_2
276    6752
428    6662
250    6071
427    5036
401    3736
       ...
123       1
884       1
V60       1
843       1
927       1
Name: count, Length: 749, dtype: int64

=== diag_3 ===
diag_3
250    11555
401     8289
276     5175
428     4577
427     3955
       ...
14         1
750        1
370        1
671        1
971        1
Name: count, Length: 790, dtype: int64

=== number_diagnoses ===
number_diagnoses
9     49474
5     11393
8     10616
7     10393
6     10161
4      5537
3      2835
2      1023
1       219
16       45
10       17
13       16
11       11
15       10
12        9
14        7
Name: count, dtype: int64

=== max_glu_serum ===
max_glu_serum
NaN     96420
Norm     2597
>200     1485
>300     1264
Name: count, dtype: int64

=== A1Cresult ===
A1Cresult
NaN     84748
>8       8216
Norm     4990
>7       3812
Name: count, dtype: int64

=== metformin ===
metformin
No        81778
Steady    18346
Up         1067
Down        575
Name: count, dtype: int64

=== repaglinide ===
repaglinide
No        100227
Steady      1384
Up           110
Down          45
Name: count, dtype: int64

=== nateglinide ===
nateglinide
No        101063
Steady       668
Up            24
Down          11
Name: count, dtype: int64

=== chlorpropamide ===
chlorpropamide
No        101680
Steady        79
Up             6
Down           1
Name: count, dtype: int64

=== glimepiride ===
glimepiride
No        96575
Steady     4670
Up          327
Down        194
Name: count, dtype: int64

=== acetohexamide ===
acetohexamide
No        101765
Steady         1
Name: count, dtype: int64

=== glipizide ===
glipizide
No        89080
Steady    11356
Up          770
Down        560
Name: count, dtype: int64

=== glyburide ===
glyburide
No        91116
Steady     9274
Up          812
Down        564
Name: count, dtype: int64

=== tolbutamide ===
tolbutamide
No        101743
Steady        23
Name: count, dtype: int64

=== pioglitazone ===
pioglitazone
No        94438
Steady     6976
Up          234
Down        118
Name: count, dtype: int64

=== rosiglitazone ===
rosiglitazone
No        95401
Steady     6100
Up          178
Down         87
Name: count, dtype: int64

=== acarbose ===
acarbose
No        101458
Steady       295
Up            10
Down           3
Name: count, dtype: int64

=== miglitol ===
miglitol
No        101728
Steady        31
Down           5
Up             2
Name: count, dtype: int64

=== troglitazone ===
troglitazone
No        101763
Steady         3
Name: count, dtype: int64

=== tolazamide ===
tolazamide
No        101727
Steady        38
Up             1
Name: count, dtype: int64

=== examide ===
examide
No    101766
Name: count, dtype: int64

=== citoglipton ===
citoglipton
No    101766
Name: count, dtype: int64

=== insulin ===
insulin
No        47383
Steady    30849
Down      12218
Up        11316
Name: count, dtype: int64

=== glyburide-metformin ===
glyburide-metformin
No        101060
Steady       692
Up             8
Down           6
Name: count, dtype: int64

=== glipizide-metformin ===
glipizide-metformin
No        101753
Steady        13
Name: count, dtype: int64

=== glimepiride-pioglitazone ===
glimepiride-pioglitazone
No        101765
Steady         1
Name: count, dtype: int64

=== metformin-rosiglitazone ===
metformin-rosiglitazone
No        101764
Steady         2
Name: count, dtype: int64

=== metformin-pioglitazone ===
metformin-pioglitazone
No        101765
Steady         1
Name: count, dtype: int64

=== change ===
change
No    54755
Ch    47011
Name: count, dtype: int64

=== diabetesMed ===
diabetesMed
Yes    78363
No     23403
Name: count, dtype: int64

=== readmitted ===
readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

## Data Cleaning

#### Input Data Cleaning

In [36]:
# Want to avoid model 'memorising' patient patterns
# Only keep latest encounter_id for duplicate patient_nbr
cleaned_df = (
    df.sort_values('encounter_id', ascending=False)
      .drop_duplicates(subset='patient_nbr', keep='first')
)

cleaned_df = cleaned_df.sort_values('encounter_id').reset_index(drop=True)

In [37]:
# Missing Data
counts = (cleaned_df == '?').sum()
counts[counts > 0]

race                  1878
weight               68671
payer_code           30085
medical_specialty    34525
diag_1                  17
diag_2                 290
diag_3                1146
dtype: int64

In [38]:
### Weight ###

# Drop weight since majority is missing
cleaned_df = cleaned_df.drop(columns=['weight'])

In [39]:
### Payer Code and Medical Specialty ###

# Too many to just add a common value or probalisitic value
# Rather reflect as no value or missing
cleaned_df['payer_code'] = cleaned_df['payer_code'].replace('?', "Missing")
cleaned_df['medical_specialty'] = cleaned_df['medical_specialty'].replace('?', "Missing")

# Drop Payer Code. Has no relevance to readmit
cleaned_df = cleaned_df.drop(columns=['payer_code'])

In [40]:
# Age column is ordinal - encode to median value
encoding = {
    '[90-100)' : 95,  
    '[80-90)'  : 85, 
    '[70-80)'  : 75,
    '[60-70)'  : 65,  
    '[50-60)'  : 55,  
    '[40-50)'  : 45,  
    '[30-40)'  : 35,     
    '[20-30)'  : 25, 
    '[10-20)'  : 15,
    '[0-10)'   : 5 
}

cleaned_df['age'] = cleaned_df['age'].apply(lambda x : encoding[x])

In [41]:
# Drop singe-value columns as they provide no variance and hence do not aid the classification problem
cleaned_df =  cleaned_df.drop(columns=['examide', 'citoglipton', 'glimepiride-pioglitazone'])

In [42]:
# Covert binary columns to 0/1
binary_map = {
    "gender": {"Female": 0, "Male": 1},
    "change": {"No": 0, "Ch": 1},
    "diabetesMed": {"No": 0, "Yes": 1}
}

for col, mapping in binary_map.items():
    cleaned_df[col] = cleaned_df[col].map(mapping)

In [43]:
# medication columns use ordinal encoding
medication_map = {"No": 0, "Steady": 1, "Up": 2, "Down": 3}

medication_cols = [
    "metformin","repaglinide","nateglinide","chlorpropamide",
    "glimepiride","acetohexamide","glipizide","glyburide","tolbutamide","pioglitazone",
    "rosiglitazone","acarbose","miglitol","troglitazone",
    "tolazamide","insulin","glyburide-metformin",
    "glipizide-metformin","metformin-rosiglitazone",
    "metformin-pioglitazone"
]

for col in medication_cols:
    cleaned_df[col] = cleaned_df[col].map(medication_map)

#### Target encoding

In [44]:
# We only interested in if they readmit within 30 days
readmit_map = {">30": 0, "NO": 0, "<30": 1}
cleaned_df["readmitted"] = cleaned_df["readmitted"].map(readmit_map)

In [45]:
cleaned_df['readmitted'].value_counts(normalize=True)

readmitted
0    0.95492
1    0.04508
Name: proportion, dtype: float64

In [46]:
for col in cleaned_df.columns:
    print(f"\n=== {col} ===")
    print(cleaned_df[col].value_counts(dropna=False))

=== encounter_id ===
encounter_id
12522        1
15738        1
16680        1
28236        1
35754        1
            ..
443847548    1
443847782    1
443854148    1
443857166    1
443867222    1
Name: count, Length: 71518, dtype: int64

=== patient_nbr ===
patient_nbr
48330783     1
63555939     1
42519267     1
89869032     1
82637451     1
            ..
100162476    1
74694222     1
41088789     1
31693671     1
175429310    1
Name: count, Length: 71518, dtype: int64

=== race ===
race
Caucasian          53538
AfricanAmerican    12915
?                   1878
Hispanic            1508
Other               1167
Asian                512
Name: count, dtype: int64

=== gender ===
gender
0.0    38023
1.0    33492
NaN        3
Name: count, dtype: int64

=== age ===
age
75    18162
65    15908
55    12349
85    11864
45     6756
35     2650
95     2040
25     1111
15      525
5       153
Name: count, dtype: int64

=== admission_type_id ===
admission_type_id
1    37191
3    13823
2    13032
6     4282
5     2859
8      303
7       19
4        9
Name: count, dtype: int64

=== discharge_disposition_id ===
discharge_disposition_id
1     43414
3      9251
6      8469
18     2398
11     1629
2      1462
22     1279
5       834
25      566
4       555
7       412
13      360
14      350
23      282
28       78
8        70
15       30
24       29
9        12
17       11
19        8
10        6
16        5
27        4
12        2
20        2
Name: count, dtype: int64

=== admission_source_id ===
admission_source_id
7     38844
1     21362
17     4895
4      2655
6      1823
2       907
5       645
20      137
3       117
9       101
8        12
10        7
22        6
14        2
11        2
25        2
13        1
Name: count, dtype: int64

=== time_in_hospital ===
time_in_hospital
3     12593
2     12310
1     10731
4      9556
5      6847
6      5107
7      3980
8      2950
9      2018
10     1587
11     1294
12      986
13      851
14      708
Name: count, dtype: int64

=== medical_specialty ===
medical_specialty
Missing                   34525
InternalMedicine          11069
Family/GeneralPractice     5021
Emergency/Trauma           4463
Cardiology                 4143
                          ...
Proctology                    1
Speech                        1
Perinatology                  1
Neurophysiology               1
Resident                      1
Name: count, Length: 70, dtype: int64

=== num_lab_procedures ===
num_lab_procedures
1      2216
43     1875
44     1708
45     1625
38     1570
       ...
120       1
104       1
121       1
126       1
118       1
Name: count, Length: 117, dtype: int64

=== num_procedures ===
num_procedures
0    31761
1    14452
2     9206
3     6986
6     3764
4     3033
5     2316
Name: count, dtype: int64

=== num_medications ===
num_medications
12    4243
13    4203
11    4051
15    4027
14    4023
      ...
69       2
75       2
81       1
79       1
74       1
Name: count, Length: 73, dtype: int64

=== number_outpatient ===
number_outpatient
0     61043
1      5347
2      2234
3      1313
4       691
5       345
6       181
7        83
8        71
9        55
10       28
11       22
12       18
13       16
14       12
15       11
16       10
17        6
21        6
20        4
18        3
22        3
35        2
29        2
36        2
25        2
24        2
19        1
26        1
27        1
37        1
40        1
33        1
Name: count, dtype: int64

=== number_emergency ===
number_emergency
0     65071
1      4678
2      1104
3       339
4       127
5        76
6        44
7        21
8        11
9         8
10        8
11        7
12        4
13        4
25        2
16        2
15        2
14        2
42        1
28        1
37        1
19        1
20        1
18        1
54        1
29        1
Name: count, dtype: int64

=== number_inpatient ===
number_inpatient
0     51717
1     12485
2      4145
3      1717
4       733
5       331
6       189
7        89
8        44
9        26
10       18
11        9
12        8
13        4
16        2
15        1
Name: count, dtype: int64

=== diag_1 ===
diag_1
414       4955
428       4061
786       2934
410       2735
486       2404
          ...
391          1
690          1
250.52       1
10           1
V51          1
Name: count, Length: 696, dtype: int64

=== diag_2 ===
diag_2
250     4784
276     4521
428     4377
427     3497
401     2957
        ...
V60        1
V55        1
843        1
E887       1
927        1
Name: count, Length: 719, dtype: int64

=== diag_3 ===
diag_3
250    8744
401    6320
276    3549
428    2969
427    2732
       ...
750       1
370       1
671       1
971       1
565       1
Name: count, Length: 747, dtype: int64

=== number_diagnoses ===
number_diagnoses
9     33491
5      8620
6      7416
8      7290
7      7280
4      4163
3      2178
2       811
1       186
16       35
13       13
10       11
11        7
15        7
12        6
14        4
Name: count, dtype: int64

=== max_glu_serum ===
max_glu_serum
NaN     68041
Norm     1759
>200      989
>300      729
Name: count, dtype: int64

=== A1Cresult ===
A1Cresult
NaN     59120
>8       5880
Norm     3752
>7       2766
Name: count, dtype: int64

=== metformin ===
metformin
0    56944
1    13347
2      798
3      429
Name: count, dtype: int64

=== repaglinide ===
repaglinide
0    70548
1      857
2       78
3       35
Name: count, dtype: int64

=== nateglinide ===
nateglinide
0    71032
1      459
2       18
3        9
Name: count, dtype: int64

=== chlorpropamide ===
chlorpropamide
0    71452
1       61
2        4
3        1
Name: count, dtype: int64

=== glimepiride ===
glimepiride
0    67833
1     3306
2      242
3      137
Name: count, dtype: int64

=== acetohexamide ===
acetohexamide
0    71517
1        1
Name: count, dtype: int64

=== glipizide ===
glipizide
0    62711
1     7905
2      552
3      350
Name: count, dtype: int64

=== glyburide ===
glyburide
0    63989
1     6555
2      586
3      388
Name: count, dtype: int64

=== tolbutamide ===
tolbutamide
0    71499
1       19
Name: count, dtype: int64

=== pioglitazone ===
pioglitazone
0    66308
1     4957
2      167
3       86
Name: count, dtype: int64

=== rosiglitazone ===
rosiglitazone
0    67118
1     4197
2      133
3       70
Name: count, dtype: int64

=== acarbose ===
acarbose
0    71332
1      178
2        7
3        1
Name: count, dtype: int64

=== miglitol ===
miglitol
0    71499
1       17
2        1
3        1
Name: count, dtype: int64

=== troglitazone ===
troglitazone
0    71516
1        2
Name: count, dtype: int64

=== tolazamide ===
tolazamide
0    71488
1       30
Name: count, dtype: int64

=== insulin ===
insulin
0    34335
1    22247
3     7729
2     7207
Name: count, dtype: int64

=== glyburide-metformin ===
glyburide-metformin
0    71044
1      461
2        8
3        5
Name: count, dtype: int64

=== glipizide-metformin ===
glipizide-metformin
0    71511
1        7
Name: count, dtype: int64

=== metformin-rosiglitazone ===
metformin-rosiglitazone
0    71516
1        2
Name: count, dtype: int64

=== metformin-pioglitazone ===
metformin-pioglitazone
0    71517
1        1
Name: count, dtype: int64

=== change ===
change
0    39510
1    32008
Name: count, dtype: int64

=== diabetesMed ===
diabetesMed
1    54196
0    17322
Name: count, dtype: int64

=== readmitted ===
readmitted
0    68294
1     3224
Name: count, dtype: int64

## Split data

In [47]:
# TimeSeriesSplit only gives you two splits
# We need 3: train, val and test
def time_series_split_3(df, n_splits=5, val_size=0.15, test_size=0.15):
    n = len(df)
    val_len = int(n * val_size)
    test_len = int(n * test_size)

    step = (n - val_len - test_len) // n_splits

    for i in range(1, n_splits + 1):
        train_end = step * i
        val_end = train_end + val_len
        test_end = val_end + test_len

        train = df.iloc[:train_end]
        val = df.iloc[train_end:val_end]
        test = df.iloc[val_end:test_end]

        yield train, val, test

## Make Model

In [48]:
# Create input and target
X_cols = cleaned_df.columns.drop(['encounter_id', 'patient_nbr', 'readmitted']).tolist()
y_col = 'readmitted'

In [49]:
# Train/Val/Test specific cleaning
# These columns need to be cleaned in each set to prevent data leakage

### Race ###
# Impute Race using probability of other types

### Diagnoses ###
# Fill diag_1, diag_2 and diag_3 with the most common value
# They have entries such as 'V45' hence we can't use median or mean
# Implement frequency encoding since each one of these cols have over 700 unique values

### Medical Speciality ###
# medical_speciality has a lot of missing, keep only top 10, group rest

class DataCleaner(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.race_probabilities_ = None
        self.diag_common_ = {}
        self.diag_frequencies_ = {}
        self.top_med_specialties_ = None

    def fit(self, X, y=None):
        X = X.copy()
        
        # 1. Learn Race Probabilities
        race_col = X['race']
        valid_race = race_col[race_col != '?']
        self.race_probabilities_ = valid_race.value_counts(normalize=True)

        # 2. Learn Diagnosis Modes & Frequencies
        for col in ["diag_1", "diag_2", "diag_3"]:
            valid_diags = X.loc[X[col] != '?', col]
            self.diag_common_[col] = valid_diags.mode().iloc[0]                                 # Get most common diagnoses
            self.diag_frequencies_[col] = valid_diags.value_counts(normalize=True)              # Get frequencies of diagnoses

        # 3. Learn Top 10 Specialties
        self.top_med_specialties_ = X['medical_specialty'].value_counts().nlargest(10).index
        
        return self

    def transform(self, X):
        X = X.copy()

        # --- Apply Race Imputation ---
        race_empty = X['race'] == '?'
        if race_empty.any():
            X.loc[race_empty, 'race'] = np.random.choice(
                self.race_probabilities_.index,
                size=race_empty.sum(),
                p=self.race_probabilities_.values
            )

        # --- Apply Diagnosis Cleaning ---
        for col in ["diag_1", "diag_2", "diag_3"]:
            # Replace '?' with most common value
            X[col] = X[col].replace('?', self.diag_common_[col])
            # Map frequencies learned in fit (unseen values get 0)
            X[col] = X[col].map(self.diag_frequencies_[col]).fillna(0)

        # --- Apply Medical Specialty Grouping ---
        X['medical_specialty'] = X['medical_specialty'].where(
            X['medical_specialty'].isin(self.top_med_specialties_), 
            'Other'
        )

        return X

In [ ]:
def make_model(dummyclassifier=False, learning_rate=1e-4):
    # Normalize numeric columns
    numeric_cols = [
        "age","time_in_hospital","num_lab_procedures","num_procedures",
        "num_medications","number_outpatient","number_emergency",
        "number_inpatient","diag_1","diag_2","diag_3","number_diagnoses"
    ]

    # One-hot encode categorical columns with few unique values and no order
    categorical_cols = [
        "race","admission_type_id","discharge_disposition_id","admission_source_id", 'medical_specialty', "max_glu_serum","A1Cresult"
    ]

    preprocessor = ColumnTransformer([
        ("num", StandardScaler(), numeric_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
    ])
    
    if dummyclassifier:
        model = DummyClassifier(strategy="prior",random_state=42)
    else:
        model = SGDClassifier(loss="log_loss", learning_rate="constant", eta0=learning_rate, class_weight="balanced", random_state=42)

    return Pipeline([
        ("cleaner", DataCleaner()),
        ("prep", preprocessor),
        ("model", model)
    ])

In [51]:
def run_model(dummyclassifier=False, learning_rate=1e-4):
    start_time = time.perf_counter()
    results = []

    for fold, (train_df, val_df, test_df) in enumerate(
            time_series_split_3(cleaned_df, n_splits=5, val_size=0.15, test_size=0.15)):

        X_train, y_train = train_df[X_cols], train_df[y_col]
        X_val, y_val = val_df[X_cols], val_df[y_col]
        X_test, y_test = test_df[X_cols], test_df[y_col]

        model = make_model(dummyclassifier=dummyclassifier, learning_rate=learning_rate)
        model.fit(X_train, y_train)

        # Get probabilities not class labels
        y_train_proba = model.predict_proba(X_train)[:, 1]
        y_val_proba = model.predict_proba(X_val)[:, 1]
        y_test_proba = model.predict_proba(X_test)[:, 1]

        # Compute ROC AUC
        roc_train = roc_auc_score(y_train, y_train_proba)
        roc_val = roc_auc_score(y_val, y_val_proba)
        roc_test = roc_auc_score(y_test, y_test_proba)

        # Compute PR AUC
        pr_train = average_precision_score(y_train, y_train_proba)
        pr_val = average_precision_score(y_val, y_val_proba)
        pr_test = average_precision_score(y_test, y_test_proba)

        # Get Recall at Precision >= 0.8 for Val
        precision, recall, thresholds = precision_recall_curve(y_val, y_val_proba)
        valid = precision[:-1] >= 0.8

        if np.any(valid):
            best_recall = recall[:-1][valid].max()
            print("Recall at Precision ≥ 0.8:", best_recall)
        else:
            print("Precision never reaches 0.8")

        results.append((fold, roc_train, pr_train, roc_val, pr_val, roc_test, pr_test))

    end_time = time.perf_counter()
    runtime = end_time - start_time

    return results, runtime

## Baseline Model

In [56]:
print("Baseline Classifier \n")

results, runtime = run_model(dummyclassifier=True)
results_df = pd.DataFrame(results, columns=["fold", "roc_train", "pr_train", "roc_val", "pr_val", "roc_test", "pr_test"])

print(f'\n Runtime: {runtime} s \n')
print(results_df)
print("\n Mean test ROC_AUC:", results_df["roc_test"].mean())
print("Mean test PR_AUC:", results_df["pr_test"].mean())

Baseline Classifier

Precision never reaches 0.8
Precision never reaches 0.8
Precision never reaches 0.8
Precision never reaches 0.8
Precision never reaches 0.8

 Runtime: 1.5239611000288278 s

   fold  roc_train  pr_train  roc_val    pr_val  roc_test   pr_test
0     0        0.5  0.047343      0.5  0.050993       0.5  0.059476
1     1        0.5  0.048592      0.5  0.059290       0.5  0.038687
2     2        0.5  0.051838      0.5  0.042137       0.5  0.031975
3     3        0.5  0.049391      0.5  0.032069       0.5  0.024611
4     4        0.5  0.045925      0.5  0.025636       0.5  0.060595

 Mean test ROC_AUC: 0.5
Mean test PR_AUC: 0.04306889158198938

## SGD Sensitivity: 3 Fixed Learning Rates

In [57]:
# eta0 = 1e-4
print("SGD Classifier with eta0=1e-4 \n")
results, runtime = run_model(learning_rate=1e-4)
results_df = pd.DataFrame(results, columns=["fold", "roc_train", "pr_train", "roc_val", "pr_val", "roc_test", "pr_test"])

print(f'\nRuntime: {runtime} s \n')
print(results_df)
print("\nMean train PR_AUC:", results_df["pr_train"].mean())
print("Mean val PR_AUC:", results_df["pr_val"].mean())
print("Mean test PR_AUC:", results_df["pr_test"].mean())

SGD Classifier with eta0=1e-4

Precision never reaches 0.8
Precision never reaches 0.8
Recall at Precision ≥ 0.8: 0.0022123893805309734
Recall at Precision ≥ 0.8: 0.0029069767441860465
Precision never reaches 0.8

Runtime: 2.257864800048992 s

   fold  roc_train  pr_train   roc_val    pr_val  roc_test   pr_test
0     0   0.764991  0.143585  0.708190  0.124012  0.701136  0.139519
1     1   0.760846  0.145819  0.728742  0.147875  0.691603  0.089577
2     2   0.746475  0.144951  0.676955  0.095891  0.671024  0.064014
3     3   0.745310  0.140834  0.708691  0.081498  0.667618  0.047883
4     4   0.725790  0.121494  0.689866  0.059387  0.639881  0.105895

Mean train PR_AUC: 0.13933668128437798
Mean val PR_AUC: 0.10173265921275917
Mean test PR_AUC: 0.08937766825823591

In [58]:
# eta0 = 1e-3
print("SGD Classifier with eta0=1e-3 \n")
results, runtime = run_model(learning_rate=1e-3)
results_df = pd.DataFrame(results, columns=["fold", "roc_train", "pr_train", "roc_val", "pr_val", "roc_test", "pr_test"])

print(f'\nRuntime: {runtime} s \n')
print(results_df)
print("\nMean train PR_AUC:", results_df["pr_train"].mean())
print("Mean val PR_AUC:", results_df["pr_val"].mean())
print("Mean test PR_AUC:", results_df["pr_test"].mean())

SGD Classifier with eta0=1e-3

Precision never reaches 0.8
Precision never reaches 0.8
Recall at Precision ≥ 0.8: 0.0022123893805309734
Recall at Precision ≥ 0.8: 0.0029069767441860465
Precision never reaches 0.8

Runtime: 2.164649099984672 s

   fold  roc_train  pr_train   roc_val    pr_val  roc_test   pr_test
0     0   0.790596  0.159988  0.724317  0.135854  0.707809  0.140542
1     1   0.781191  0.163745  0.736173  0.149921  0.724066  0.099633
2     2   0.764486  0.160304  0.704771  0.106344  0.690162  0.071012
3     3   0.758144  0.145227  0.718139  0.080694  0.677428  0.046571
4     4   0.748722  0.134112  0.704674  0.062307  0.643868  0.109514

Mean train PR_AUC: 0.15267511113119586
Mean val PR_AUC: 0.10702398432186344
Mean test PR_AUC: 0.09345447303134177

In [59]:
# eta0 = 1e-2
print("SGD Classifier with eta0=1e-2 \n")
results, runtime = run_model(learning_rate=1e-2)
results_df = pd.DataFrame(results, columns=["fold", "roc_train", "pr_train", "roc_val", "pr_val", "roc_test", "pr_test"])

print(f'\nRuntime: {runtime} s \n')
print(results_df)
print("\nMean train PR_AUC:", results_df["pr_train"].mean())
print("Mean val PR_AUC:", results_df["pr_val"].mean())
print("Mean test PR_AUC:", results_df["pr_test"].mean())

SGD Classifier with eta0=1e-2

Precision never reaches 0.8
Precision never reaches 0.8
Precision never reaches 0.8
Recall at Precision ≥ 0.8: 0.0029069767441860465
Precision never reaches 0.8

Runtime: 1.9061126999440603 s

   fold  roc_train  pr_train   roc_val    pr_val  roc_test   pr_test
0     0   0.749019  0.142269  0.668049  0.108565  0.637271  0.111831
1     1   0.760646  0.136914  0.722470  0.127962  0.696496  0.078383
2     2   0.734099  0.133092  0.693110  0.089383  0.646173  0.052480
3     3   0.727216  0.127771  0.684716  0.079632  0.646055  0.044617
4     4   0.682779  0.110951  0.642108  0.053242  0.608758  0.098745

Mean train PR_AUC: 0.13019947114504765
Mean val PR_AUC: 0.09175680798008694
Mean test PR_AUC: 0.0772110162257846

## Grid Search over SGD Hyperparameters

In [ ]:
# Define parameter Grid

param_grid = {
    "model__eta0": [1e-4,3e-4,1e-3,3e-3,1e-2],
    "model__alpha": [1e-6,1e-5,1e-4,1e-3],
    "model__penalty":["l2", "l1"],
    "model__class_weight": [None, "balanced"]
}